project:
  type: website

website:
  title: "TestWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - NewWebpage.qmd
      - ThirdPage.qmd
      - about.qmd

format:
  html:
  respect-user-color-scheme: true
 theme:
  light: flatly
  dark: darkly
      - brand
    css: styles.css
    toc: true
execute: 
  freeze: auto
  


